### ISSUE TITLE
Investigate angular-cli integration

### ISSUE THREAD

**Issue by brandonroberts** [ngrx/router#121]
Needs to be easier to setup using the angular-cli with external dependencies. File generation commands would be nice also.

**Comment by kylecordes** [comment]
To help anyone who needs to set it up manually in the meantime, here are the chunks you need.  it is pretty tedious, though actually I believe this problem is entirely to be solved in the CLI, I don't think it is reasonable even possible for individual libraries to take responsibility for wiring up the CLI.

To fetch the library:

```
npm install @ngrx/router @ngrx/core --save
```

In system-config.ts:

```
const map: any = {
  '@ngrx': 'vendor/@ngrx',
  'query-string': 'vendor/query-string',
  "strict-uri-encode": "vendor/strict-uri-encode",
  "object-assign": "vendor/object-assign",
  "path-to-regexp": "vendor/path-to-regexp"
};

/** User packages configuration. */
const packages: any = {
  "@ngrx/router": { main: 'index' },
  "@ngrx/core": { main: 'index' },
  "query-string": { main: 'index' },
  "strict-uri-encode": { main: 'index' },
  "object-assign": { main: 'index' },
  "path-to-regexp": { main: 'index' }
};
```

In angular-cli-build.js:

```
      '@ngrx/**/*.+(js|js.map)',
      'query-string/*.+(js|js.map)',
      'strict-uri-encode/*.+(js|js.map)',
      'object-assign/*.+(js|js.map)',
      'path-to-regexp/*.+(js|js.map)',
```

**Comment by kylecordes** [comment]
@brandonroberts I see you included this information in your PR that just got merged. Excellent!

https://github.com/ngrx/router/commit/2acc88c563aa72d2ad6b08cb65748ff74ff7aca8

**Comment by brandonroberts** [comment]
Thanks for your help!
