### ISSUE TITLE
ngrx/router vs official router

### ISSUE THREAD

**Issue by benbro** [ngrx/router#147]
Hi,

The angular blog post says the official router is a successor of ngrx/router.
Does it means that this project is deprecated and it's better to use the official router in a new project?
http://angularjs.blogspot.co.il/2016/06/improvements-coming-for-routing-in.html

Thanks

**Comment by littleStudent** [comment]
I think the new official router has a bit to go. Seeing some people in gitter talking about problems and staying with ngrx/router till it settles down.
Since they are both very similar it will be very easy to switch from ngrx/router to the official one. 

The ngrx/router team will write a blogpost (at least thats what i heard), to clear up where the project is going. I guess it will be maintained, but not too much new features will be implemented?

**Comment by benbro** [comment]
Thanks
Please tell me If I should ask questions like this in a different place.
