### ISSUE TITLE
Investigate Universal support for status codes

### ISSUE THREAD

**Issue by MikeRyan52** [ngrx/router#55]
There are a couple of PRs out right now that should make it easier for ngrx/router to support other platforms: angular/angular#7984 and angular/angular#7962

We want ngrx/router's Universal support to be feature complete with addition of being able to send status codes (301 for redirects, 404 for not found, etc). We are not quite sure how to go about this yet and it may require work on our end to add this support to Universal.

cc @gdi2290

**Comment by tamascsaba** [comment]
big :+1:

**Comment by MikeRyan52** [comment]
I spoke to @gdi2290 and @jeffwhelpley at ng-conf about this. It seems that the best way to go is for ngrx/router to create an Express / Koa compatible middleware that wraps Angular/Universal's API.

We'll be exploring this more in the coming weeks.

**Comment by jeffwhelpley** [comment]
Let me know if you guys have any questions as you get into things. To provide some more context, the reason why I suggested to Mike to have the ngrx router at a higher level above Universal is because we continue to move more and more from Universal to core. I would like to avoid having any downstream dependencies from Universal other than core. Also, I think it will make things a lot easier for you guys to have the most control at the very top of the food chain. I am available to chat online if you want to work out a more detailed design.
